spring.application.name=money-tracker

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=money_tracker;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sua_senha
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-sgfp-2026}

# Server
server.port=8080
